version: '0.2'
ignorePaths:
  - .gitignore
  - eslint.config.mjs
  - parameters.json
  - .vscode/*.json
dictionaryDefinitions:
  - name: regional
    description: 한국 및 해외 지명
    path: .cspell/regional.txt
    scope: workspace
    addWords: false
  - name: technical
    path: .cspell/technical.txt
    addWords: true
dictionaries:
  - regional
  - technical
words:
  - adwords
  - asana
  - cnet
  - convio
  - dongminyu
  - dotenv
  - flickr
  - jumpit
  - pharma
  - recommendee
ignoreWords: []
import: []
useGitignore: true
allowCompoundWords: true
