version: "0.2"
ignorePaths:
  - .gitignore
  - eslint.config.mjs
  - parameters.json
dictionaryDefinitions:
  - name: regional
    description: 한국 및 해외 지명
    path: .cspell/custom-dictionary-workspace.txt
    scope: workspace
    addWords: false
dictionaries:
  - regional
words: [dongminyu]
ignoreWords: []
import: []
useGitignore: true
allowCompoundWords: true
