version: '0.2'
ignorePaths:
  - .gitignore
  - eslint.config.mjs
  - parameters.json
  - .vscode/*.json
dictionaryDefinitions:
  - name: regional
    description: 한국 및 해외 지명
    path: .cspell/regional.txt
    scope: workspace
    addWords: false
  - name: technical
    path: .cspell/technical.txt
    addWords: true
  - name: job-domain
    path: .cspell/job-domain.txt
    addWords: false
dictionaries:
  - regional
  - technical
  - job-domain
  - en-gb
  - node
  - npm
  - typescript
  - softwareTerms
  - filetypes
  - fonts
words:
  - adwords
  - asana
  - cnet
  - convio
  - dongmin
  - dongminyu
  - dotenv
  - flickr
  - gitmoji
  - jumpit
  - pharma
  - recommendee
  - saramin
  - wanted
ignoreWords: []
import: []
useGitignore: true
allowCompoundWords: false
