version: '0.2'
ignorePaths:
  - .gitignore
  - eslint.config.mjs
  - parameters.json
  - .vscode/*.json
dictionaryDefinitions:
  - name: regional
    description: 한국 및 해외 지명
    path: .cspell/regional.txt
    scope: workspace
    addWords: false
dictionaries:
  - regional
words: [dongminyu, pharma, recommendee]
ignoreWords: []
import: []
useGitignore: true
allowCompoundWords: true
