name: discord-wanted

concurrency:
  group: discord-wanted
  cancel-in-progress: true

permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semantic-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: 🤖 Ensure Commit is Semantic
        if: github.event_name == 'pull_request'
        uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: false
          ignoreLabels: |
            bot
            ignore-semantic-pull-request
          wip: false

  spell-check:
    defaults:
      run:
        working-directory: .

    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4

      - name: 🪄 Spell Check
        uses: streetsidesoftware/cspell-action@v6
        with:
          incremental_files_only: false
          root: .
          verbose: false
